fix: don't use fastmath
FAUST fastmath implementation causes error with GCC >= 14.2.1:

    fastmath.cpp:212:33: error: initializer element is not constant

Signed-off-by: Christopher Arndt <chris@chrisarndt.de>